env:
  global:
    # - PACKAGE_VERSION="$(node -p -e 'require("./package.json").version')"
    - PACKAGE_VERSION=0.0.3
language: node_js

node_js:
  - 10

script:
  - echo go

before_deploy:
  - npm install -g vsce
  - vsce package

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    name: "zsdoc-${PACKAGE_VERSION}"
    on:
      repo: zsdoc
      tags: true