env:
  global:
    - PACKAGE_VERSION=`node -p -e 'require("./package.json").version'`
language: node_js

node_js:
  - 10

script:
  - echo package version...
  - echo $PACKAGE_VERSION

before_deploy:
  - npm install -g vsce
  - vsce package

deploy:
  - provider: releases
    api_key:
      secure: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    name: "gdoc-${PACKAGE_VERSION}"
    email: dillonliang@163.com
    on:
      repo: dillonliang224/gdoc
      tags: true